name: check_syntax

on:
  push:
    branches:
      - main

jobs:
  check_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: set version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: update pip
      run: |
        python -m pip install --upgrade pip
    - name: flake install
      run: pip install flake8

    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1

    - name: show python version
      run: python --version

     
