name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows - latest, ubuntu - latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: version_setup
      uses: actions/setup-python@v2
      with: 
        python-version: ${{matrix.python}}
        if: matrix.os == 'ubuntu-latest' && matrix.python != '3.10'

    - name: PIP_Update
      run: |
        python -m pip install --upgrade pip
    
    - name: unittest_flake8_install
      run: |
          python -m pip install flake8 unittest
          
    - name: show python version
      run: python --version

    - name: flake8_run
      run: flake8

    - name: unittest
      run: python -m unittest discover
